---
name: pre-commit

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: set PYTHON_VERSION
        run: -|
          echo "PYTHON_VERSION=$(grep python .tool-versions \
          cut -d ' ' -f1)" >> $GITHUB_ENV
      - uses: actions/setup-python@v2
        with:
          # see: https://github.com/actions/python-versions/releases
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: pre-commit/action@v2.0.3
        with:
          extra_args: -a --show-diff-on-failure
