name: pre-commit

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10.2" # see: https://github.com/actions/python-versions/releases
      - uses: pre-commit/action@v2.0.3
        with:
          extra_args: -a --show-diff-on-failure
